### ISSUE TITLE
Feature request: add option to also fail CI

### ISSUE THREAD

**Issue by paoloricciuti** [ghostdevv/svelte-check-action#17]
Currently we are already running svelte check on CI and we are failing the check if svelte check fails. This adds visibility to the output which i think is cool but i think there's should be an option to also fail CI.

**Comment by ghostdevv** [comment]
I wonder if an option like this should only fail if there are errors in the PR (i.e. filtering the errors like we do for the comment) or fail if there are any errors in the entire check - or maybe both with a option like `failOnError: 'scoped' | 'all'`

**Comment by paoloricciuti** [comment]
> I wonder if an option like this should only fail if there are errors in the PR (i.e. filtering the errors like we do for the comment) or fail if there are any errors in the entire check - or maybe both with a option like `failOnError: 'scoped' | 'all'`

Ugh this is a tough one. We had occasions when updating a dependency was making svelte-check fail...an option would be cool but then it could be confusing if ci fails and there's no comment in the pr.

Also just thought of this but maybe a change to package.json or package lock should avoid the filtering all together

**Comment by ghostdevv** [comment]
I think the best solution will be to respect a filter option and have the `failOnError`, so I've impl #6 to add that and will work on this next :pray:

> Also just thought of this but maybe a change to package.json or package lock should avoid the filtering all together

I can't think of a situation where you would have a path set that wouldn't cause a changed `package.json` - if you're referring to `package.json`s that are outside one of the provided `paths`, then I'd probably prefer to keep the behaviour simple here and assume that it doesn't have side effects

**Comment by paoloricciuti** [comment]
> I can't think of a situation where you would have a path set that wouldn't cause a changed `package.json`

I'm not sure I understand...if I install some new version of some package types might change causing svelte check errors. Those errors are not in the package.json itself so svelte check will still fail but there will be 0 comments from this action.

Am I missing something?

**Comment by ghostdevv** [comment]
This has been added in [v1.2.0](https://github.com/ghostdevv/svelte-check-action/releases/tag/v1.2.0)! I went with just adding a boolean for `failOnError` since I think it would be weird if the comment is disconnected with whether it fails. You can effectively control whether it always fails or not by enabling `failOnError` and using `filterChanges` option.

> I'm not sure I understand...if I install some new version of some package types might change causing svelte check errors. Those errors are not in the package.json itself so svelte check will still fail but there will be 0 comments from this action.

Ah I see what you mean - I think in that context you would want to disable `filterChanges` such that all errors found are reported. The original idea was just to report on changes that are related to the current PR but the scope has grown which is why that option exists!

**Comment by ghostdevv** [comment]
On reflection it'd be nice to be able to disable the filtering, because we have other benefits like the GitHub comment. I opened #39 for this
